version: "3.7"
services:
    # db:
    #     image: mysql:5.7
    #     ports:
    #         - "3306:3306"
    #     restart: always
    #     env_file:
    #         - .env.development
    db:
        image: postgres:12-alpine
        ports:
            - "5432:5432"
        restart: always
        env_file:
            - .env
    redis:
        depends_on:
            - db
        image: "redis:6-alpine"
        ports:
            - "6379:6379"
        command: ["redis-server", "--bind", "redis", "--port", "6379"]
    app:
        depends_on:
            - redis
        build: .
        restart: always
        ports:
            - 5000:5000
        env_file:
            - .env
